services:
  backend:
    build: .
    container_name: node_app_proj6
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=db_proj6
    depends_on:
      - postgres
      - redis
    restart: always
  redis:
    image: redis:7
    container_name: redis
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_proj6
    ports:
      - "5432:5432"
