name: CI pipeline

on:
    push:
        branches: [ "proj6" ]
jobs:
    test-build:
        runs-on: ubuntu-latest

        steps:
            - name: Recup le code
              uses: actions/checkout@v3
 
            - name: installer node
              uses: actions/setup-node@v3
              with:
                  node-version: 20

            - name: installer les dépendances
              run: npm install
              working-directory: .

            - name: build docker
              run: docker build -t proj6

            - name: connexion docker hub
              run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u
                  "${{secrets.DOCKER_USERNAME}}" --password-stdin
            
            - name : push image
              run : | 
                docker tag myapp ${{ secrets.DOCKER_USERNAME }}/proj6:latest
                docker push ${{ secrets.DOCKER_USERNAME }}/proj6:latest