name: CI/CD pipeline

on:
  push:
    branches: ["main"]
jobs:
  test-build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Recup le code
        uses: actions/checkout@v3

      - name: installer node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: installer les dépendances
        run: npm install
        working-directory: proj4

      - name: build docker image
        run: docker build -t myapp ./proj4

      - name: login dockerhub
        run: echo"${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin

      - name: Push image
        run: |
          docker tag myapp ${{ secrets.DOCKER_USERNAME }}/myapp:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest
